apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048-deployment
  labels:
    app: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-2048
        image: azlanmalik/game-2048:v1
        ports:
        - containerPort: 80
